services:
    mysong_core.block.unit:
        class: Mysong\CoreBundle\Block\UnitBlockService
        arguments: [mysong_core.block.unit, "@templating"]
        tags:
            - { name: sonata.block }
