imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_admin.yml }

parameters:
    locale: fr
    locales:
        - fr
        - en
        - es
        - de
    domain_host: web-widget.net.dev
    google_analytics_ua: UA-116502-9
    google_client_id: -
    google_client_secret: -
    facebook_client_id: -
    facebook_client_secret: -
    github_client_id: -
    github_client_secret: -
    twitter_client_id: -
    twitter_client_secret: -
    twitter_client_id: -
    twitter_client_secret: -

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        google_analytics_ua: "%google_analytics_ua%"
        google_client_id: "%google_client_id%"
        google_client_secret: "%google_client_secret%"
        facebook_client_id: "%facebook_client_id%"
        facebook_client_secret: "%facebook_client_secret%"
        github_client_id: "%github_client_id%"
        github_client_secret: "%github_client_secret%"
        twitter_client_id: "%twitter_client_id%"
        twitter_client_secret: "%twitter_client_secret%"


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [CmfCreateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration (needed for Jackalope Doctrine DBAL)
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        path:     "%database_path%"

# Doctrine PHPCR-ODM configuration
doctrine_phpcr:
    session:
        backend: "%phpcr_backend%"
        workspace: "%phpcr_workspace%"
        username: "%phpcr_user%"
        password: "%phpcr_password%"
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"

# Jackalope Metadata and Node Cache services
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

# Cmf Configuration
cmf_core:
    persistence:
        phpcr:
            enabled: true
        # if you want another basepath
        # basepath: /custom/basepath
    publish_workflow: false

# Cmf Routing Configuration
cmf_routing:
    dynamic:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page: MysongCoreBundle:Page:index.html.twig


# simple cms
cmf_simple_cms:
    persistence:
        phpcr:
            enabled:          true
            basepath:         /cms/simple
            manager_registry: doctrine_phpcr
            manager_name:     ~
            document_class:   Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page
            use_sonata_admin: auto
            sonata_admin:
                sort: false
    use_menu: auto
#

# Menu Configuration
knp_menu:
    twig: true
#

# Internationalisation
lunetics_locale:
    allowed_locales: "%locales%"
    guessing_order:
        - router
        - browser
cmf_core:
    multilang:
        locales: "%locales%"
doctrine_phpcr:
    odm:
        # ...
        locales:
            en: [fr, es, de]
            fr: [en, es, de]
            es: [en, fr, de]
            de: [en, fr, es]
        locale_fallback: hardcoded
sonata_admin:
    # ...
    templates:
            user_block: MysongCoreBundle:Admin:admin_topnav.html.twig
# Fin internationalisation

# Cmf Create Configuration
fos_rest:
    view:
        formats:
            json: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
