# app/config/sonata/admin_config.yml
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts: [admin]

sonata_admin:
    dashboard:
        blocks:
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
            - { position: right, type: sonata.admin.block.admin_list }

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        #Acme\BasicCmsBundle\Document\Page:
        #    valid_children:
        #        - Acme\BasicCmsBundle\Document\Post
        #Acme\BasicCmsBundle\Document\Post:
        #    valid_children: []
        # ...

# CMF Sonata Admin
# Disable the RoutingBundle admin
# as the routes are managed by the RoutingAutoBundle and not the administrator
cmf_routing:
    # ...
    dynamic:
        # ...
        persistence:
            phpcr:
                # ...
                use_sonata_admin: false